#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine it’s executed on
# a different way using ifconfig but now ip is a new command and ifconfig can be missing in some os
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'

ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
